import { CalendarDays, Download, UserCheck } from "lucide-react";
import { useState } from "react";
import { Metric, PageHeading, Status, Toolbar } from "@/components/ui/PageBits";

const attendance = [{ name: "Sarah Jenkins", team: "Product", checkIn: "08:54 AM", checkOut: "05:42 PM", status: "Present" }, { name: "Marcus Chen", team: "Engineering", checkIn: "09:12 AM", checkOut: "--", status: "Present" }, { name: "Priya Shah", team: "People", checkIn: "--", checkOut: "--", status: "On leave" }, { name: "Daniel Okafor", team: "Finance", checkIn: "08:47 AM", checkOut: "05:31 PM", status: "Present" }, { name: "Elena Rossi", team: "Marketing", checkIn: "--", checkOut: "--", status: "Absent" }];

export default function AttendancePage() {
  const [query, setQuery] = useState("");
  const rows = attendance.filter((row) => `${row.name} ${row.team}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="mx-auto max-w-[1440px]"><PageHeading eyebrow="Daily operations" title="Attendance" description="Monitor today's attendance and keep your team in sync." action={<div className="flex gap-2"><button className="inline-flex items-center gap-2 rounded-lg border border-[#e6e0e5] bg-white px-4 py-2.5 text-sm font-bold text-[#756c75]"><Download size={16} />Export</button><button className="inline-flex items-center gap-2 rounded-lg bg-[#714b67] px-4 py-2.5 text-sm font-bold text-white"><CalendarDays size={16} />September 5, 2026</button></div>} /><div className="grid gap-4 sm:grid-cols-3"><Metric label="Present today" value="112" detail="90.3%" tone="green" /><Metric label="Late arrivals" value="8" detail="6.4%" tone="amber" /><Metric label="On leave" value="4" detail="3.2%" tone="plum" /></div><div className="mt-6 rounded-xl border border-[#e6e0e5] bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.04)]"><div className="mb-5 flex items-center gap-3"><UserCheck className="text-[#714b67]" size={22} /><div><h2 className="text-lg font-bold text-[#352f37]">Today's log</h2><p className="text-sm text-[#9c8e99]">Updated moments ago</p></div></div><Toolbar onSearch={setQuery} placeholder="Search employees" /><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead className="border-b border-[#eee9ed] text-xs uppercase tracking-wider text-[#9c8e99]"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Check in</th><th className="px-4 py-3">Check out</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-[#f0ebef]">{rows.map((row) => <tr key={row.name}><td className="px-4 py-4"><p className="text-sm font-bold text-[#352f37]">{row.name}</p><p className="text-xs text-[#9c8e99]">{row.team}</p></td><td className="px-4 py-4 text-sm text-[#756c75]">{row.checkIn}</td><td className="px-4 py-4 text-sm text-[#756c75]">{row.checkOut}</td><td className="px-4 py-4"><Status>{row.status}</Status></td></tr>)}</tbody></table></div></div></div>;
}
