import { ArrowUpRight, CalendarCheck2, Clock3, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { Metric, Status, money } from "@/components/ui/PageBits";

const tasks = [{ title: "Review time-off requests", count: "4 pending", to: "/time-off" }, { title: "Run September payroll", count: "Due in 5 days", to: "/payroll" }, { title: "Complete employee records", count: "3 missing details", to: "/employees" }];

export default function DashboardPage() {
  return (
    <div className="mx-auto max-w-[1440px]">
      <div className="mb-8 flex items-end justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-[#9c8e99]">Monday, September 5, 2026</p><h1 className="text-4xl font-bold tracking-tight text-[#5c3a54]">Good morning, Alex</h1><p className="mt-2 text-sm text-[#756c75]">Here is what is happening across your people operations today.</p></div><span className="hidden rounded-full border border-[#e6e0e5] bg-white px-3 py-2 text-xs font-bold text-[#756c75] sm:block">September 2026</span></div>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total employees" value="124" detail="+6.4%" tone="plum" /><Metric label="Present today" value="112" detail="90.3%" tone="green" /><Metric label="Pending leave" value="4" detail="Needs review" tone="amber" /><Metric label="Next payroll" value={money(1842000)} detail="Sep 30" tone="blue" /></div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className="rounded-xl border border-[#e6e0e5] bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.04)]"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-lg font-bold text-[#352f37]">Workforce snapshot</h2><p className="mt-1 text-sm text-[#9c8e99]">A quick look at your current workforce</p></div><Link to="/employees" className="text-sm font-bold text-[#714b67]">View team <ArrowUpRight className="ml-1 inline" size={15} /></Link></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg bg-[#fbf8fa] p-4"><Users size={20} className="text-[#714b67]" /><p className="mt-5 text-2xl font-bold text-[#352f37]">86</p><p className="text-xs text-[#9c8e99]">Full time</p></div><div className="rounded-lg bg-[#fbf8fa] p-4"><Clock3 size={20} className="text-[#3d6f99]" /><p className="mt-5 text-2xl font-bold text-[#352f37]">22</p><p className="text-xs text-[#9c8e99]">Part time</p></div><div className="rounded-lg bg-[#fbf8fa] p-4"><CalendarCheck2 size={20} className="text-[#27804d]" /><p className="mt-5 text-2xl font-bold text-[#352f37]">16</p><p className="text-xs text-[#9c8e99]">On leave</p></div></div><div className="mt-7"><div className="mb-2 flex justify-between text-xs font-bold text-[#756c75]"><span>Attendance this month</span><span>92.4%</span></div><div className="h-2 overflow-hidden rounded-full bg-[#f0ebef]"><div className="h-full w-[92%] rounded-full bg-[#714b67]" /></div></div></section><section className="rounded-xl border border-[#e6e0e5] bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.04)]"><h2 className="text-lg font-bold text-[#352f37]">Workspace tasks</h2><p className="mt-1 text-sm text-[#9c8e99]">Items that need your attention</p><div className="mt-5 space-y-2">{tasks.map((task) => <Link key={task.title} to={task.to} className="flex items-center justify-between rounded-lg border border-transparent bg-[#fbf8fa] p-4 transition hover:border-[#e6e0e5] hover:bg-white"><div><p className="text-sm font-bold text-[#352f37]">{task.title}</p><p className="mt-1 text-xs text-[#9c8e99]">{task.count}</p></div><ArrowUpRight size={17} className="text-[#714b67]" /></Link>)}</div></section></div>
      <section className="mt-6 rounded-xl border border-[#e6e0e5] bg-white p-6 shadow-[0_1px_3px_rgba(0,0,0,0.04)]"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-bold text-[#352f37]">Recent activity</h2><p className="mt-1 text-sm text-[#9c8e99]">The latest changes in your workspace</p></div><Status>Completed</Status></div><div className="grid gap-4 md:grid-cols-3"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#eef8f2] text-xs font-bold text-[#27804d]">SJ</span><p className="text-sm text-[#756c75]"><strong className="text-[#352f37]">Sarah Jenkins</strong> updated her bank details.<span className="block pt-1 text-xs text-[#b2a6ae]">12 minutes ago</span></p></div><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#f3edf2] text-xs font-bold text-[#714b67]">AM</span><p className="text-sm text-[#756c75]"><strong className="text-[#352f37]">You</strong> approved a time-off request.<span className="block pt-1 text-xs text-[#b2a6ae]">1 hour ago</span></p></div><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#eef5fb] text-xs font-bold text-[#3d6f99]">PR</span><p className="text-sm text-[#756c75]"><strong className="text-[#352f37]">Payroll</strong> report was generated.<span className="block pt-1 text-xs text-[#b2a6ae]">Yesterday</span></p></div></div></section>
    </div>
  );
}
