import { ArrowLeft, BriefcaseBusiness, CalendarDays, FileText, Mail, MapPin, Pencil, Phone, UserRound, type LucideIcon } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { PageHeading, Status } from "@/components/ui/PageBits";
import { findDemoEmployee } from "@/features/employees/data";
import type { ReactNode } from "react";

export default function EmployeeDetailsPage() {
  const { employeeId = "" } = useParams();
  const navigate = useNavigate();
  const employee = findDemoEmployee(employeeId);
  if (!employee) return <div className="mx-auto max-w-3xl rounded-xl border border-[#e6e0e5] bg-white p-8"><h1 className="text-xl font-bold text-[#352f37]">Employee not found</h1><Link className="mt-4 inline-block text-sm font-bold text-[#714b67]" to="/employees">Back to employees</Link></div>;
  const initials = employee.fullName.split(" ").map((part) => part[0]).join("");
  const smartButtons: [string, string, LucideIcon][] = [["Contracts", "contracts", FileText], ["Attendance", "attendance", CalendarDays], ["Time off", "time-off", BriefcaseBusiness], ["Allocations", "time-off", FileText]];
  return <div className="mx-auto max-w-[1100px]"><button onClick={() => navigate("/employees")} className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-[#714b67]"><ArrowLeft size={16} /> Back to employees</button><PageHeading eyebrow="Employee profile" title={employee.fullName} description={`${employee.positionId} · ${employee.departmentId}`} action={<button onClick={() => navigate(`/employees/${employee.id}/edit`)} className="inline-flex items-center gap-2 rounded-lg bg-[#714b67] px-4 py-2.5 text-sm font-bold text-white"><Pencil size={16} /> Edit employee</button>} /><div className="grid gap-6 lg:grid-cols-[1fr_1.5fr]"><section className="rounded-xl border border-[#e6e0e5] bg-white p-6"><div className="flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-full bg-[#f3edf2] text-xl font-bold text-[#714b67]">{initials}</span><div><h2 className="text-xl font-bold text-[#352f37]">{employee.fullName}</h2><p className="text-sm text-[#9c8e99]">{employee.id}</p><div className="mt-2"><Status>{employee.employmentStatus === "active" ? "Active" : "Inactive"}</Status></div></div></div><div className="mt-7 space-y-4 text-sm"><p className="flex items-center gap-3 text-[#756c75]"><Mail size={17} className="text-[#714b67]" /> {employee.fullName.toLowerCase().replace(" ", ".")}@peoplepay.test</p><p className="flex items-center gap-3 text-[#756c75]"><Phone size={17} className="text-[#714b67]" /> +91 98765 43210</p><p className="flex items-center gap-3 text-[#756c75]"><MapPin size={17} className="text-[#714b67]" /> Bengaluru, India</p></div></section><section className="rounded-xl border border-[#e6e0e5] bg-white p-6"><h2 className="text-lg font-bold text-[#352f37]">Work information</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><Info icon={<BriefcaseBusiness size={17} />} label="Department" value={employee.departmentId ?? "Unassigned"} /><Info icon={<UserRound size={17} />} label="Job position" value={employee.positionId ?? "Unassigned"} /><Info icon={<CalendarDays size={17} />} label="Joining date" value="January 15, 2024" /><Info icon={<MapPin size={17} />} label="Manager / location" value="Alex Morgan · Bengaluru" /></div></section></div><div className="mt-6 grid gap-4 sm:grid-cols-4">{smartButtons.map(([label, path, Icon]) => <Link key={label} to={`/${path}?employee=${employee.id}`} className="flex items-center gap-3 rounded-xl border border-[#e6e0e5] bg-white p-4 text-sm font-bold text-[#714b67] hover:border-[#714b67]"> <Icon size={18} />{label}</Link>)}</div></div>;
}

function Info({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#9c8e99]">{icon}{label}</p><p className="mt-2 text-sm font-semibold text-[#352f37]">{value}</p></div>; }
