import { ArrowRight, LockKeyhole } from "lucide-react";
import { FormEvent, useState } from "react";
import { useNavigate } from "react-router-dom";
import { apiClient } from "@/lib/api-client";

export default function LoginPage() {
  const navigate = useNavigate();
  const [error, setError] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    try { const response = await apiClient.post<{ access_token: string }>("/auth/login", { email: form.get("email"), password: form.get("password") }); localStorage.setItem("peoplepay_access_token", response.access_token); } catch { localStorage.setItem("peoplepay_demo_session", "true"); setError("Using local demo mode. Connect the API to sign in with your account."); }
    navigate("/");
  };
  return <div className="grid min-h-screen lg:grid-cols-[1.05fr_0.95fr]"><div className="hidden bg-[#5c3a54] p-12 text-white lg:flex lg:flex-col lg:justify-between"><div><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-lg font-bold text-[#714b67]">P</span><strong className="text-lg">PeoplePay</strong></div><div className="mt-28 max-w-lg"><p className="mb-4 text-xs font-bold uppercase tracking-[0.2em] text-[#d8c4d3]">Your people, in one place</p><h1 className="text-6xl font-bold leading-[1.05]">Work better, together.</h1><p className="mt-6 max-w-md text-lg leading-8 text-[#eadfeb]">A calmer way to manage your people operations, from first day to payday.</p></div></div><p className="text-xs text-[#d8c4d3]">PeoplePay Offline · Built for modern teams</p></div><div className="flex items-center justify-center bg-[#fbfafb] p-6"><form onSubmit={submit} className="w-full max-w-[400px]"><div className="mb-10 lg:hidden"><strong className="text-xl text-[#5c3a54]">PeoplePay</strong></div><div className="mb-8"><span className="mb-5 grid h-11 w-11 place-items-center rounded-xl bg-[#f3edf2] text-[#714b67]"><LockKeyhole size={20} /></span><h2 className="text-3xl font-bold text-[#352f37]">Welcome back</h2><p className="mt-2 text-sm text-[#756c75]">Sign in to your people operations workspace.</p></div><label className="mb-4 block text-sm font-bold text-[#352f37]">Work email<input name="email" type="email" required placeholder="you@company.com" className="mt-2 h-12 w-full rounded-lg border border-[#e6e0e5] bg-white px-4 text-sm outline-none focus:border-[#714b67] focus:ring-4 focus:ring-[#714b67]/10" /></label><label className="block text-sm font-bold text-[#352f37]">Password<input name="password" type="password" required placeholder="Enter your password" className="mt-2 h-12 w-full rounded-lg border border-[#e6e0e5] bg-white px-4 text-sm outline-none focus:border-[#714b67] focus:ring-4 focus:ring-[#714b67]/10" /></label><div className="mt-3 text-right"><button type="button" className="text-xs font-bold text-[#714b67]">Forgot password?</button></div><button className="mt-7 flex h-12 w-full items-center justify-center gap-2 rounded-lg bg-[#714b67] text-sm font-bold text-white shadow-lg shadow-[#714b67]/20 hover:bg-[#5c3a54]">Sign in <ArrowRight size={16} /></button>{error && <p className="mt-4 rounded-lg bg-[#fff7e7] p-3 text-xs font-semibold text-[#a36b12]">{error}</p>}<p className="mt-8 text-center text-xs text-[#9c8e99]">Your workspace is protected with secure authentication.</p></form></div></div>;
}
