import { ArrowLeft, Download, FileText } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { PageHeading, Status, Toolbar, money } from "@/components/ui/PageBits";
import { apiClient, downloadFile } from "@/lib/api-client";
import type { Payslip } from "@/types";

export default function PayslipsPage() {
  const [payslips, setPayslips] = useState<Payslip[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [query, setQuery] = useState("");
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  useEffect(() => {
    apiClient
      .get<Payslip[]>("/payslips/")
      .then(setPayslips)
      .catch((err) => setError(err instanceof Error ? err.message : "Could not load payslips."))
      .finally(() => setLoading(false));
  }, []);

  const filtered = payslips.filter((p) => `${p.employeeName} ${p.period}`.toLowerCase().includes(query.toLowerCase()));

  const download = (payslip: Payslip) => {
    setDownloadingId(payslip.id);
    downloadFile(`/payslips/${payslip.id}/pdf`, `payslip-${payslip.employeeName.replace(/\s+/g, "_")}-${payslip.periodYear}-${String(payslip.periodMonth).padStart(2, "0")}.pdf`)
      .catch((err) => setError(err instanceof Error ? err.message : "Could not download payslip."))
      .finally(() => setDownloadingId(null));
  };

  return (
    <div className="mx-auto max-w-[1300px]">
      <Link to="/payroll" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-[#714b67]">
        <ArrowLeft size={16} /> Back to payroll
      </Link>
      <PageHeading eyebrow="Payroll / payslips" title="Payslips" description="Every payslip generated by a payroll run." />

      <Toolbar onSearch={setQuery} placeholder="Search by employee or period" />

      {error && <p className="mb-4 rounded-lg bg-[#fdecec] p-3 text-sm font-semibold text-[#b3261e]">{error}</p>}

      <div className="overflow-hidden rounded-xl border border-[#e6e0e5] bg-white">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[720px] text-left">
            <thead className="border-b border-[#eee9ed] bg-[#fbf8fa] text-xs uppercase tracking-wider text-[#9c8e99]">
              <tr>
                <th className="px-6 py-4">Employee</th>
                <th className="px-6 py-4">Period</th>
                <th className="px-6 py-4">Gross</th>
                <th className="px-6 py-4">Net</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4" />
              </tr>
            </thead>
            <tbody className="divide-y divide-[#f0ebef]">
              {loading && (
                <tr><td colSpan={6} className="px-6 py-8 text-center text-sm text-[#9c8e99]">Loading...</td></tr>
              )}
              {!loading && filtered.length === 0 && (
                <tr><td colSpan={6} className="px-6 py-8 text-center text-sm text-[#9c8e99]">No payslips yet — run payroll to generate some.</td></tr>
              )}
              {filtered.map((payslip) => (
                <tr key={payslip.id}>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <span className="grid h-9 w-9 place-items-center rounded-full bg-[#f3edf2] text-xs font-bold text-[#714b67]">
                        {payslip.employeeName.split(" ").map((part) => part[0]).join("")}
                      </span>
                      <span className="text-sm font-bold text-[#352f37]">{payslip.employeeName}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4 text-sm text-[#756c75]">{payslip.period}</td>
                  <td className="px-6 py-4 text-sm text-[#756c75]">{money(payslip.grossSalary)}</td>
                  <td className="px-6 py-4 text-sm font-bold text-[#352f37]">{money(payslip.netSalary)}</td>
                  <td className="px-6 py-4"><Status>{payslip.status === "paid" ? "Paid" : "Generated"}</Status></td>
                  <td className="px-6 py-4 text-right">
                    <button
                      onClick={() => download(payslip)}
                      disabled={downloadingId === payslip.id}
                      className="inline-flex items-center gap-1.5 text-sm font-bold text-[#714b67] disabled:opacity-50"
                    >
                      {downloadingId === payslip.id ? <FileText size={14} /> : <Download size={14} />}
                      {downloadingId === payslip.id ? "Preparing..." : "Download PDF"}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
