import { Check, Plus, X } from "lucide-react";
import { useState } from "react";
import { PageHeading, Status, Toolbar } from "@/components/ui/PageBits";
import type { TimeOffRequest } from "@/types";

const initialRequests: TimeOffRequest[] = [{ id: "LV-204", employeeName: "Sarah Jenkins", type: "Annual leave", dates: "Sep 12 - Sep 16, 2026", days: 5, status: "Pending" }, { id: "LV-203", employeeName: "Marcus Chen", type: "Personal day", dates: "Sep 9, 2026", days: 1, status: "Pending" }, { id: "LV-202", employeeName: "Priya Shah", type: "Annual leave", dates: "Sep 2 - Sep 4, 2026", days: 3, status: "Approved" }, { id: "LV-201", employeeName: "Daniel Okafor", type: "Sick leave", dates: "Aug 29, 2026", days: 1, status: "Approved" }];

export default function TimeOffPage() {
  const [requests, setRequests] = useState(initialRequests);
  const [query, setQuery] = useState("");
  const update = (id: string, status: "Approved" | "Rejected") => setRequests((current) => current.map((request) => request.id === id ? { ...request, status } : request));
  const filtered = requests.filter((request) => `${request.employeeName} ${request.type}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="mx-auto max-w-[1440px]"><PageHeading eyebrow="Requests & approvals" title="Time off" description="Review leave requests and keep availability visible across the team." action={<button className="inline-flex items-center gap-2 rounded-lg bg-[#714b67] px-4 py-2.5 text-sm font-bold text-white"><Plus size={17} />Request time off</button>} /><div className="mb-5 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-[#e6e0e5] bg-white p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#9c8e99]">Pending review</p><p className="mt-2 text-2xl font-bold text-[#a36b12]">4</p></div><div className="rounded-xl border border-[#e6e0e5] bg-white p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#9c8e99]">Approved this month</p><p className="mt-2 text-2xl font-bold text-[#27804d]">18</p></div><div className="rounded-xl border border-[#e6e0e5] bg-white p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#9c8e99]">Days out this week</p><p className="mt-2 text-2xl font-bold text-[#714b67]">7</p></div></div><Toolbar onSearch={setQuery} placeholder="Search requests" /><div className="overflow-hidden rounded-xl border border-[#e6e0e5] bg-white shadow-[0_1px_3px_rgba(0,0,0,0.04)]"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left"><thead className="border-b border-[#eee9ed] bg-[#fbf8fa] text-xs uppercase tracking-wider text-[#9c8e99]"><tr><th className="px-6 py-4">Employee</th><th className="px-6 py-4">Type</th><th className="px-6 py-4">Dates</th><th className="px-6 py-4">Days</th><th className="px-6 py-4">Status</th><th className="px-6 py-4" /></tr></thead><tbody className="divide-y divide-[#f0ebef]">{filtered.map((request) => <tr key={request.id}><td className="px-6 py-4"><p className="text-sm font-bold text-[#352f37]">{request.employeeName}</p><p className="text-xs text-[#9c8e99]">{request.id}</p></td><td className="px-6 py-4 text-sm text-[#756c75]">{request.type}</td><td className="px-6 py-4 text-sm text-[#756c75]">{request.dates}</td><td className="px-6 py-4 text-sm text-[#756c75]">{request.days}</td><td className="px-6 py-4"><Status>{request.status}</Status></td><td className="px-6 py-4 text-right">{request.status === "Pending" && <span className="inline-flex gap-1"><button onClick={() => update(request.id, "Approved")} className="rounded-md p-2 text-[#27804d] hover:bg-[#eef8f2]" aria-label="Approve request"><Check size={17} /></button><button onClick={() => update(request.id, "Rejected")} className="rounded-md p-2 text-[#b64e5b] hover:bg-[#fff0f1]" aria-label="Reject request"><X size={17} /></button></span>}</td></tr>)}</tbody></table></div></div></div>;
}
